Pass table values through our santization functions
pantheon-systems/wp_launch_check pull request #141
Opened 2023-05-05 19:39 UTC by jspellman814

2023-05-05 19:39 UTC, jspellman814 commented on php/pantheon/utils.php
> +			$rebuilt_link = '<a href="' . $sanitized_href . '">' . $sanitized_link_text . '</a>';
Need to confirm that this markup is accurate.

2023-05-08 22:19 UTC, jspellman814 commented on php/pantheon/utils.php
> +			$rebuilt_link = '<a href="' . $sanitized_href . '">' . $sanitized_link_text . '</a>';
confirmed here: https://github.com/pantheon-systems/wp_launch_check/blob/b40dd826c2fac66f91a453355f4612ba847fcca0/php/pantheon/checks/plugins.php#L57

updated markup in [99f4652](https://github.com/pantheon-systems/wp_launch_check/pull/141/commits/99f4652be8b2dcfe91f8f211746e5330a9cf5661)

2023-05-11 15:27 UTC, jazzsequence reviewed
This looks like it will sanitize links but leaves other things alone. Since the initial bug report referenced injecting scripts into `img` tags, have you tested against that and would this address that possibility?

2023-05-11 16:22 UTC, jazzsequence requested changes
When I run this locally (I've pulled your changes into #142) I get a bunch of these PHP Warnings:

`PHP Warning:  DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 142 in /app/wp_launch_check/php/pantheon/utils.php on line 67`

2023-05-16 17:01 UTC, jspellman814 commented
> This looks like it will sanitize links but leaves other things alone. Since the initial bug report referenced injecting scripts into `img` tags, have you tested against that and would this address that possibility?

Strings that are not anchor tags are being passed through the sanitizer function, which was not previously happening: https://github.com/pantheon-systems/wp_launch_check/pull/141/files#diff-23eee0c3deeae33b0160199a3fa6283310be725332dde2dc19462ebbf87bfac2R72, though after testing it seems there is still work to do here. Also looking into the issue you ran into locally... I hadn't come across that when I was testing. =

2023-05-23 18:13 UTC, pwtyler commented on php/pantheon/utils.php
> +				if ( 0 === $anchors->length ) {;
```suggestion
				if ( 0 === $anchors->length ) {
```
is this a typo? Valid just unconventional?

2023-05-24 21:00 UTC, jazzsequence approved these changes
Tested against the steps in the bugs ticket. WFM :shipit:

2023-05-25 14:51 UTC, merged